// <auto-generated />
namespace PolyStone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlterUserColSurName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterUserColSurName));
        
        string IMigrationMetadata.Id
        {
            get { return "201811270648594_AlterUserCol-SurName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
